### ISSUE TITLE
README

### ISSUE THREAD

**Issue by rye** [frc2503/r2015#2]
The README needs detailed instructions regarding setup and other installation things.  This will probably need to be copied over from year-to-year for future robot programs.

**Comment by rye** [comment]
Since I know the most about this program, I'll self-assign.

**Comment by tjuranek** [comment]
Where might I view the README?

**Comment by rye** [comment]
I haven't made much progress on this, but you can look at the README as-is (on the `master` branch) at [github.com/frc2503/r2015](https://github.com/frc2503/r2015)&mdash;GitHub will automatically display the README in any directory of a project, rendered as Markdown, which I will cover at our meeting tomorrow. Further work on the README will be done on the `readme` branch. You can view _that_ version of the README at [github.com/frc2503/r2015/tree/readme](https://github.com/frc2503/r2015/tree/readme).

**Comment by rye** [comment]
To view _just_ the README, you can go to [github.com/frc2503/r2015/blob/master/README.md](https://github.com/frc2503/r2015/blob/master/README.md) (master) or [github.com/frc2503/r2015/blob/readme/README.md](https://github.com/frc2503/r2015/blob/readme/README.md) (the newer version of the README as progress is made on it).

**Comment by rye** [comment]
I plan to finish the README stuff tonight in preparation for the meeting tomorrow.

**Comment by rye** [comment]
Pretty much done now, @TJuranek. Let me know if you find any problems or if something needs clarification. :cookie: for reminding me :smile:

**Comment by tjuranek** [comment]
Looks great @rye!
